name: Specs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  spec:
    runs-on: ubuntu-latest
    name: spec
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - name: Run tests
        run: |
          cp dotenv.example .env
          bundle exec rspec --color --format documentation
